import { collection, doc, setDoc } from "firebase/firestore";
import { db } from "../firebase";

const now = Date.now();

const calgaryRestaurants = [
  {
    id: "ship-anchor",
    name: "Ship & Anchor Pub",
    address: "534 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.4,
    priceLevel: "$$",
    about: "A lively local pub known for craft beer, live music, and patio vibes.",
    offers: "Happy Hour 3–6pm daily. Weekly trivia nights.",
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "national-10th",
    name: "National on 10th",
    address: "341 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.2,
    priceLevel: "$$",
    about: "Massive bar with bowling, rooftop patio, and DJ nights.",
    offers: "Late night happy hour. Weekend DJ events.",
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "craft-beer-market",
    name: "Craft Beer Market",
    address: "345 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.3,
    priceLevel: "$$",
    about: "Huge beer selection with modern pub-style food.",
    offers: "Rotating taps. Daily food specials.",
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    createdAt: now,
  },
  {
    id: "trolley-5",
    name: "Trolley 5",
    address: "728 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.1,
    priceLevel: "$$",
    about: "Microbrewery with rooftop patio and live music nights.",
    offers: "Local brews + weekend events.",
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "pinbar",
    name: "PinBar",
    address: "501 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.0,
    priceLevel: "$",
    about: "Arcade bar with retro pinball machines.",
    offers: "Drink specials during arcade tournaments.",
    hasHappyHour: false,
    hasDailySpecials: true,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "cowboys",
    name: "Cowboys Dance Hall",
    address: "421 12 Ave SE, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 3.9,
    priceLevel: "$$",
    about: "Country-themed nightclub with large dance floor.",
    offers: "Weekly themed dance nights.",
    hasHappyHour: false,
    hasDailySpecials: false,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "greta-bar",
    name: "Greta Bar",
    address: "213 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.3,
    priceLevel: "$$",
    about: "Arcade bar with street food and cocktails.",
    offers: "Game tokens with drink purchase.",
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "hayden-block",
    name: "Hayden Block",
    address: "1136 Kensington Rd NW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.5,
    priceLevel: "$$",
    about: "BBQ joint with whiskey bar.",
    offers: "BBQ platters and rotating whiskey menu.",
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    createdAt: now,
  },
  {
    id: "blanco-cantina",
    name: "Blanco Cantina",
    address: "723 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.0,
    priceLevel: "$$",
    about: "Mexican street food and tequila bar.",
    offers: "Taco Tuesdays + margarita specials.",
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    createdAt: now,
  },
  {
    id: "bottlescrew-bills",
    name: "Bottlescrew Bill’s",
    address: "140 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.1,
    priceLevel: "$$",
    about: "Global beer selection with pub atmosphere.",
    offers: "Passport beer nights.",
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: true,
    createdAt: now,
  },
  {
    id: "rose-crown",
    name: "Rose & Crown Pub",
    address: "1503 4 St SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.0,
    priceLevel: "$$",
    about: "Classic British-style pub.",
    offers: "Live music weekends.",
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    createdAt: now,
  },
  {
  id: "cold-garden",
  name: "Cold Garden Beverage Co.",
  address: "1100 11 St SE, Calgary, AB",
  cityId: "calgary",
  ownerUid: null,
  rating: 4.6,
  priceLevel: "$$",
  about: "Popular Inglewood brewery with colorful decor and relaxed vibes.",
  offers: "Rotating craft beers and seasonal releases.",
  hasHappyHour: true,
  hasDailySpecials: false,
  hasEvents: true,
  createdAt: now,
},
{
  id: "unicorn-pub",
  name: "The Unicorn Pub",
  address: "223 8 Ave SW, Calgary, AB",
  cityId: "calgary",
  ownerUid: null,
  rating: 4.1,
  priceLevel: "$$",
  about: "Multi-level pub with dance floor and late-night DJ events.",
  offers: "Student nights and weekend DJ parties.",
  hasHappyHour: true,
  hasDailySpecials: false,
  hasEvents: true,
  createdAt: now,
},
{
  id: "home-and-away",
  name: "Home & Away",
  address: "1207 1 St SW, Calgary, AB",
  cityId: "calgary",
  ownerUid: null,
  rating: 4.3,
  priceLevel: "$$",
  about: "Sports bar with big screens, pub food, and vibrant atmosphere.",
  offers: "Game-day specials and wing nights.",
  hasHappyHour: true,
  hasDailySpecials: true,
  hasEvents: false,
  createdAt: now,
},
];

export async function seedCalgaryRestaurants() {
  const colRef = collection(db, "restaurants");

  for (const r of calgaryRestaurants) {
    await setDoc(doc(colRef, r.id), r, { merge: true });
  }

  console.log("Calgary restaurants seeded");
  return calgaryRestaurants.length;
}