import { collection, doc, setDoc } from "firebase/firestore";
import { db } from "../firebase";

const now = Date.now();

const standardHours = {
  monday: { open: "11:00", close: "23:00", closed: false },
  tuesday: { open: "11:00", close: "23:00", closed: false },
  wednesday: { open: "11:00", close: "23:00", closed: false },
  thursday: { open: "11:00", close: "23:00", closed: false },
  friday: { open: "11:00", close: "01:00", closed: false },
  saturday: { open: "10:00", close: "01:00", closed: false },
  sunday: { open: "10:00", close: "22:00", closed: false },
};

const calgaryRestaurants = [
  {
    id: "ship-anchor",
    name: "Ship & Anchor Pub",
    address: "534 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.4,
    ratingCount: 120,
    priceLevel: "$$",
    about: "A lively local pub known for craft beer, live music, and patio vibes.",
    offers: "Happy Hour 3–6pm daily. Weekly trivia nights.",
    phone: "403-555-0101",
    website: "https://www.shipandanchor.com",
    hours: {
      ...standardHours,
      friday: { open: "11:00", close: "02:00", closed: false },
      saturday: { open: "10:00", close: "02:00", closed: false },
    },
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: true,
    happyHourDetails: "Mon–Fri 3–6pm: $6 pints, $5 highballs, $10 nachos.",
    dailySpecialsDetails: "Tues: Taco Night • Thurs: Wing Night • Sun: Burger + beer deal.",
    events: [
      { title: "Trivia Night", day: "Wednesday", time: "7:00 PM", details: "Teams up to 6. Prizes for top 3 teams." },
      { title: "Live Indie Band", day: "Friday", time: "9:30 PM", details: "No cover before 10pm." },
    ],
    createdAt: now,
  },

  {
    id: "national-10th",
    name: "National on 10th",
    address: "341 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.2,
    ratingCount: 98,
    priceLevel: "$$",
    about: "Massive bar with bowling, rooftop patio, and DJ nights.",
    offers: "Late night happy hour. Weekend DJ events.",
    phone: "403-555-0102",
    website: "https://www.ntnl.ca",
    hours: {
      ...standardHours,
      friday: { open: "11:00", close: "02:00", closed: false },
      saturday: { open: "10:00", close: "02:00", closed: false },
    },
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    happyHourDetails: "Daily 4–6pm: $7 cocktails, $5 beer.",
    dailySpecialsDetails: "",
    events: [
      { title: "DJ Saturdays", day: "Saturday", time: "10:00 PM", details: "Top 40 + hip hop." },
    ],
    createdAt: now,
  },

  {
    id: "craft-beer-market",
    name: "Craft Beer Market",
    address: "345 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.3,
    ratingCount: 105,
    priceLevel: "$$",
    about: "Huge beer selection with modern pub-style food.",
    offers: "Rotating taps. Daily food specials.",
    phone: "403-555-0103",
    website: "https://www.craftbeermarket.ca",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    happyHourDetails: "Mon–Fri 2–5pm: $5 drafts.",
    dailySpecialsDetails: "Daily chef’s special + beer pairing.",
    events: [],
    createdAt: now,
  },

  {
    id: "trolley-5",
    name: "Trolley 5",
    address: "728 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.1,
    ratingCount: 88,
    priceLevel: "$$",
    about: "Microbrewery with rooftop patio and live music nights.",
    offers: "Local brews + weekend events.",
    phone: "403-555-0104",
    website: "https://www.trolley5.com",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: true,
    happyHourDetails: "Mon–Fri 3–6pm: $6 house beers.",
    dailySpecialsDetails: "Wing Wednesdays + Sunday brunch deal.",
    events: [
      { title: "Live Band Night", day: "Friday", time: "8:30 PM", details: "Local Calgary bands." },
    ],
    createdAt: now,
  },

  {
    id: "pinbar",
    name: "PinBar",
    address: "501 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.0,
    ratingCount: 65,
    priceLevel: "$",
    about: "Arcade bar with retro pinball machines.",
    offers: "Drink specials during arcade tournaments.",
    phone: "403-555-0105",
    website: "https://www.pinbar.ca",
    hours: {
      ...standardHours,
      monday: { open: "", close: "", closed: true },
    },
    hasHappyHour: false,
    hasDailySpecials: true,
    hasEvents: true,
    happyHourDetails: "",
    dailySpecialsDetails: "Sunday arcade free-play hour.",
    events: [
      { title: "Pinball Tournament", day: "Saturday", time: "7:00 PM", details: "Winner gets free drink vouchers." },
    ],
    createdAt: now,
  },

  {
    id: "cowboys",
    name: "Cowboys Dance Hall",
    address: "421 12 Ave SE, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 3.9,
    ratingCount: 140,
    priceLevel: "$$",
    about: "Country-themed nightclub with large dance floor.",
    offers: "Weekly themed dance nights.",
    phone: "403-555-0106",
    website: "https://www.cowboysdancehall.com",
    hours: {
      monday: { open: "", close: "", closed: true },
      tuesday: { open: "", close: "", closed: true },
      wednesday: { open: "20:00", close: "01:00", closed: false },
      thursday: { open: "20:00", close: "02:00", closed: false },
      friday: { open: "19:00", close: "02:00", closed: false },
      saturday: { open: "19:00", close: "02:00", closed: false },
      sunday: { open: "", close: "", closed: true },
    },
    hasHappyHour: false,
    hasDailySpecials: false,
    hasEvents: true,
    happyHourDetails: "",
    dailySpecialsDetails: "",
    events: [
      { title: "Country Night", day: "Friday", time: "9:00 PM", details: "Line dancing + country DJ." },
    ],
    createdAt: now,
  },

  {
    id: "greta-bar",
    name: "Greta Bar",
    address: "213 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.3,
    ratingCount: 111,
    priceLevel: "$$",
    about: "Arcade bar with street food and cocktails.",
    offers: "Game tokens with drink purchase.",
    phone: "403-555-0107",
    website: "https://www.gretabar.com",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    happyHourDetails: "Daily 4–6pm: $7 cocktails.",
    dailySpecialsDetails: "",
    events: [
      { title: "Arcade Tournament", day: "Saturday", time: "8:00 PM", details: "Sign up at 7:30pm." },
    ],
    createdAt: now,
  },

  {
    id: "hayden-block",
    name: "Hayden Block",
    address: "1136 Kensington Rd NW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.5,
    ratingCount: 126,
    priceLevel: "$$",
    about: "BBQ joint with whiskey bar.",
    offers: "BBQ platters and rotating whiskey menu.",
    phone: "403-555-0108",
    website: "https://www.haydenblockyyc.com",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    happyHourDetails: "Mon–Fri 3–5pm: $6 draft beers.",
    dailySpecialsDetails: "Brisket sandwich combo special.",
    events: [],
    createdAt: now,
  },

  {
    id: "blanco-cantina",
    name: "Blanco Cantina",
    address: "723 17 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.0,
    ratingCount: 94,
    priceLevel: "$$",
    about: "Mexican street food and tequila bar.",
    offers: "Taco Tuesdays + margarita specials.",
    phone: "403-555-0109",
    website: "https://www.blancocantina.ca",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    happyHourDetails: "Mon–Thu 2–5pm: $6 margaritas.",
    dailySpecialsDetails: "Taco Tuesday $4 tacos.",
    events: [],
    createdAt: now,
  },

  {
    id: "bottlescrew-bills",
    name: "Bottlescrew Bill’s",
    address: "140 10 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.1,
    ratingCount: 72,
    priceLevel: "$$",
    about: "Global beer selection with pub atmosphere.",
    offers: "Passport beer nights.",
    phone: "403-555-0110",
    website: "https://www.bottlescrewbills.com",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: true,
    happyHourDetails: "Daily 3–6pm: $5 draft beer.",
    dailySpecialsDetails: "Wing Night Thursdays.",
    events: [
      { title: "Beer Passport Night", day: "Thursday", time: "7:00 PM", details: "Sample beers from around the world." },
    ],
    createdAt: now,
  },

  {
    id: "rose-crown",
    name: "Rose & Crown Pub",
    address: "1503 4 St SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.0,
    ratingCount: 70,
    priceLevel: "$$",
    about: "Classic British-style pub.",
    offers: "Live music weekends.",
    phone: "403-555-0111",
    website: "https://www.roseandcrown.ca",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    happyHourDetails: "Mon–Fri 4–6pm: $6 pints.",
    dailySpecialsDetails: "",
    events: [
      { title: "Live Music", day: "Saturday", time: "9:00 PM", details: "Local bands." },
    ],
    createdAt: now,
  },

  {
    id: "cold-garden",
    name: "Cold Garden Beverage Co.",
    address: "1100 11 St SE, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.6,
    ratingCount: 133,
    priceLevel: "$$",
    about: "Popular Inglewood brewery with colorful decor and relaxed vibes.",
    offers: "Rotating craft beers and seasonal releases.",
    phone: "403-555-0112",
    website: "https://www.coldgarden.ca",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    happyHourDetails: "Daily 3–6pm: $6 pints, $7 seasonal pours.",
    dailySpecialsDetails: "",
    events: [
      { title: "Taproom Bingo", day: "Tuesday", time: "7:00 PM", details: "Free to play. Prizes every round." },
    ],
    createdAt: now,
  },

  {
    id: "unicorn-pub",
    name: "The Unicorn Pub",
    address: "223 8 Ave SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.1,
    ratingCount: 84,
    priceLevel: "$$",
    about: "Multi-level pub with dance floor and late-night DJ events.",
    offers: "Student nights and weekend DJ parties.",
    phone: "403-555-0113",
    website: "https://www.theunicornpub.com",
    hours: {
      ...standardHours,
      friday: { open: "11:00", close: "02:00", closed: false },
      saturday: { open: "10:00", close: "02:00", closed: false },
    },
    hasHappyHour: true,
    hasDailySpecials: false,
    hasEvents: true,
    happyHourDetails: "Mon–Fri 4–6pm: $5 bottles + $8 mixed drinks.",
    dailySpecialsDetails: "",
    events: [
      { title: "Throwback DJ Night", day: "Friday", time: "10:00 PM", details: "2000s hits + requests." },
    ],
    createdAt: now,
  },

  {
    id: "home-and-away",
    name: "Home & Away",
    address: "1207 1 St SW, Calgary, AB",
    cityId: "calgary",
    ownerUid: null,
    rating: 4.3,
    ratingCount: 109,
    priceLevel: "$$",
    about: "Sports bar with big screens, pub food, and vibrant atmosphere.",
    offers: "Game-day specials and wing nights.",
    phone: "403-555-0114",
    website: "https://www.homeandawayyyc.com",
    hours: standardHours,
    hasHappyHour: true,
    hasDailySpecials: true,
    hasEvents: false,
    happyHourDetails: "Mon–Fri 3–6pm: $6 beers, $9 apps.",
    dailySpecialsDetails: "Mon: Wing Night • Wed: Burger Deal • Sat: Game-day platter.",
    events: [],
    createdAt: now,
  },
];

export async function seedCalgaryRestaurants() {
  const colRef = collection(db, "restaurants");

  for (const r of calgaryRestaurants) {
    await setDoc(doc(colRef, r.id), r, { merge: true });
  }

  console.log("Calgary restaurants seeded/updated");
  return calgaryRestaurants.length;
}